---

- name: '[mailsvr] Create a directory if it does not exist'
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /data/GoOne/
    - /data/GoOne/mailsvr/
    - /data/GoOne/logs/
    - /data/GoOne/logs/mailsvr
  tags: 'mailsvr_init'
- name: '[mailsvr] Copy scripts'
  copy:
    src: ./scripts/server.sh
    dest: /data/GoOne/mailsvr/server.sh
    mode: '0755'
  tags: "mailsvr_init"

- name: '[mailsvr] Copy bin'
  copy:
    src: ../build/mailsvr
    dest: /data/GoOne/mailsvr/mailsvr
    mode: '755'
    backup: yes
  tags: "mailsvr_push"

- name: '[mailsvr] start mailsvr'
  shell: cd /data/GoOne/mailsvr; ./server.sh start; ./server.sh check
  ignore_errors: yes
  tags: 'mailsvr_start'

- name: '[mailsvr] stop mailsvr'
  shell: cd /data/GoOne/mailsvr; ./server.sh stop
  ignore_errors: yes
  tags: 'mailsvr_stop'

- name: '[mailsvr] restart mailsvr'
  shell: cd /data/GoOne/mailsvr; ./server.sh restart; ./server.sh check
  ignore_errors: yes
  tags: 'mailsvr_restart'

- name: '[mailsvr] check mailsvr'
  shell: cd /data/GoOne/mailsvr; ./server.sh check
  ignore_errors: yes
  tags: 'mailsvr_check'

- name: '[mailsvr] delLog mailsvr'
  shell: cd /data/GoOne/logs/mailsvr; rm ./*
  ignore_errors: yes
  tags: 'mailsvr_delLog'